/**
 * Generates firmware/esp32/lib/core/pipeline_config.h from the browser's
 * current (calibrated) config + calibration stats — the "train on the
 * website, bake into the ESP32" workflow. Field names and structure match
 * that file exactly; see its own header comment for the standalone (Mode
 * B) build instructions this output feeds into.
 */
import type { BciConfig } from "./config";
import type { CalibrationStats } from "./types";

export function generatePipelineConfigHeader(config: BciConfig, stats: CalibrationStats): string {
  const line = (name: string, value: string | number | boolean) => `  ${typeof value === "boolean" ? "bool" : "double"} ${name} = ${value};`;

  return `// Standalone (Mode B) pipeline configuration — GENERATED by the BCI Hand
// Configurator web app's Calibration page ("Export ESP32 Config") on
// ${new Date().toISOString()}.
//
// This is the tuned output of a real calibration session: drop this file
// in place of firmware/esp32/lib/core/pipeline_config.h, then build with
//     pio run -e esp32dev_standalone
// See docs/ESP32_SETUP.md "Mode B" and docs/CALIBRATION.md.
//
// Calibration trial counts this was derived from: ${stats.nRestTrials} REST,
// ${stats.nSingleTrials} SINGLE_BLINK (${stats.nSingleCandidates} detected),
// ${stats.nDoubleTrials} DOUBLE_BLINK (${stats.nDoublePairs} pairs detected).
#pragma once

namespace bcihand {

struct PipelineConfig {
  // acquisition — fixed at 256 Hz to match the compiled-in filter
  // coefficients (lib/core/dsp_coeffs.h); do not change without
  // regenerating those via scripts/generate_esp32_filter_coeffs.py.
${line("fsHz", 256.0)}

  // dsp
${line("baselineTrackerTimeConstantS", config.dsp.baselineTrackerTimeConstantS)}
${line("notchEnabled", config.dsp.notchEnabled)}

  // spatial
${line("af7Af8MinCorrelation", config.spatial.af7Af8MinCorrelation)}
${line("af7Af8MaxAmplitudeRatio", config.spatial.af7Af8MaxAmplitudeRatio)}

  // candidate_detection (min_blink_width_s / max_blink_width_s / min_prominence_uv
  // derived from your SINGLE_BLINK calibration trials)
${line("thresholdMadMultiplier", config.candidateDetection.thresholdMadMultiplier)}
${line("minBlinkWidthS", config.candidateDetection.minBlinkWidthS)}
${line("maxBlinkWidthS", config.candidateDetection.maxBlinkWidthS)}
${line("minProminenceUv", config.candidateDetection.minProminenceUv)}
${line("refractoryAfterCandidateS", config.candidateDetection.refractoryAfterCandidateS)}
${line("reboundGuardS", config.candidateDetection.reboundGuardS)}
${line("reboundRefractoryS", config.candidateDetection.reboundRefractoryS)}

  // double_blink (interval bounds derived from your DOUBLE_BLINK calibration trials)
${line("doubleBlinkMinIntervalS", config.doubleBlink.minIntervalS)}
${line("doubleBlinkMaxIntervalS", config.doubleBlink.maxIntervalS)}
${line("doubleBlinkWaitForSecondTimeoutS", config.doubleBlink.waitForSecondTimeoutS)}
${line("doubleBlinkRefractoryAfterDoubleS", config.doubleBlink.refractoryAfterDoubleS)}

  // confidence
${line("highConfidenceThreshold", config.confidence.highConfidenceThreshold)}
${line("mediumConfidenceThreshold", config.confidence.mediumConfidenceThreshold)}
${line("minSignalQuality", config.confidence.minSignalQuality)}

  // motion_veto
${line("motionVetoEnabled", config.motionVeto.enabled)}
${line("motionVetoAccelEnergyThresholdG2", config.motionVeto.accelEnergyThresholdG2)}
${line("motionVetoConfidencePenalty", config.motionVeto.confidencePenalty)}

  // calibration (feeds the classifier's soft-confidence scoring — see
  // lib/core/blink_classifier.h)
${line("calibrationNoiseFloorMedian", stats.noiseFloorMedian)}
${line("calibrationNoiseFloorMad", stats.noiseFloorMad)}
};

inline const PipelineConfig& activePipelineConfig() {
  static const PipelineConfig kConfig{};
  return kConfig;
}

}  // namespace bcihand
`;
}
