// AUTO-GENERATED by scripts/generate_esp32_filter_coeffs.py — do not hand-edit.
//
// Generated from config/default_config.yaml (dsp section) via the exact
// same scipy.signal.butter / scipy.signal.iirnotch calls used by
// src/bcihand/dsp/filters.py (design_bandpass_sos / design_notch_sos), so
// this embedded filter is numerically the same design as the PC pipeline's
// default configuration:
//   fs_hz              = 256.0
//   highpass_hz        = 0.5
//   lowpass_hz         = 20.0
//   filter_order       = 2
//   notch_hz           = 60.0
//   notch_quality      = 30.0
//
// If config/default_config.yaml's dsp section changes, or the Muse 2's
// real sampling rate is confirmed to differ from fallback_sample_rate_hz
// (WAITING FOR HARDWARE VERIFICATION — see docs/MUSE2_SETUP.md), re-run:
//     python scripts/generate_esp32_filter_coeffs.py
#pragma once

namespace bcihand {
namespace dsp_coeffs {

constexpr double kFsHz = 256.0;

// kBandpassSOS: 2 second-order section(s), each [b0, b1, b2, a0, a1, a2] (a0 is always 1.0).
static const double kBandpassSOS[2][6] = {
    {0.042379351917603884, 0.084758703835207769, 0.042379351917603884, 1, -1.3462460614126406, 0.5175763815781339},
    {1, -2, 1, 1, -1.9826815314312436, 0.98283811743363081},
};

// kNotchSOS: 1 second-order section(s), each [b0, b1, b2, a0, a1, a2] (a0 is always 1.0).
static const double kNotchSOS[1][6] = {
    {0.97603957335046265, -0.1913372156565939, 0.97603957335046287, 1, -0.19133721565659384, 0.95207914670092519},
};

}  // namespace dsp_coeffs
}  // namespace bcihand
