// AUTO-GENERATED by scripts/export_web_fixtures.py — do not hand-edit.
//
// Generated from config/default_config.yaml (dsp section) via the exact
// same scipy.signal.butter / scipy.signal.iirnotch calls used by
// src/bcihand/dsp/filters.py (design_bandpass_sos / design_notch_sos), so
// this is numerically the same filter design as the Python pipeline's
// default configuration (fs=256.0, highpass=0.5, lowpass=20.0,
// order=2, notch=60.0, Q=30.0).
//
// Re-run `python scripts/export_web_fixtures.py` after changing
// config/default_config.yaml's dsp section.

export const FS_HZ = 256.0;

/** Each row: [b0, b1, b2, a0, a1, a2] (a0 is always 1.0), scipy SOS format. */
export const BANDPASS_SOS: number[][] = [
  [0.042379351917603884, 0.084758703835207769, 0.042379351917603884, 1, -1.3462460614126406, 0.5175763815781339],
  [1, -2, 1, 1, -1.9826815314312436, 0.98283811743363081],
];

/** Single second-order section, same row format as BANDPASS_SOS. */
export const NOTCH_SOS: number[][] = [
  [0.97603957335046265, -0.1913372156565939, 0.97603957335046287, 1, -0.19133721565659384, 0.95207914670092519],
];
