#!/usr/bin/env python
"""Exports golden fixtures from the Python reference pipeline for the
TypeScript web port's equivalence tests (project brief sections 7/33).

Python is the golden reference. This script runs REAL, un-mocked
`SignalSimulator` + `BlinkPipeline` code and dumps deterministic
input/output pairs to JSON, which `web/src/core/*.test.ts` loads and
replays through the TypeScript port, asserting the same events, the same
classifications, and the same commands come out (within a documented
floating-point tolerance for continuous values; exact match for discrete
decisions like is_valid_blink / event_type / command).

Raw input SAMPLES (not just event summaries) are exported specifically so
this comparison does not depend on the TypeScript simulator's RNG matching
Python's PCG64 bit-for-bit — the TS port replays the exact same samples
Python generated, rather than regenerating them independently.

Run whenever config/default_config.yaml or src/bcihand/ detection/
classification logic changes:
    python scripts/export_web_fixtures.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import numpy as np  # noqa: E402

from bcihand.acquisition.simulated_source import SimulatedEEGSource  # noqa: E402
from bcihand.dsp.filters import design_bandpass_sos, design_notch_sos  # noqa: E402
from bcihand.pipeline import BlinkPipeline  # noqa: E402
from bcihand.simulation.signal_generator import build_demo_scenario  # noqa: E402
from bcihand.utils.config import load_config  # noqa: E402

WEB_CORE_DIR = Path(__file__).resolve().parents[1] / "web" / "src" / "core"
OUT_DIR = WEB_CORE_DIR / "__fixtures__"
DSP_DIR = WEB_CORE_DIR / "dsp"
FS_HZ = 256.0


def _round_list(arr, ndigits=9):
    return [round(float(v), ndigits) for v in arr]


def export_filter_coefficients(config) -> None:
    """Writes filterCoeffs.generated.ts — a PRODUCTION source file (not a
    test fixture): the actual coefficients dsp/filters.ts imports at
    runtime. Generated from the exact same scipy.signal.butter/iirnotch
    calls src/bcihand/dsp/filters.py uses, exactly like
    firmware/esp32/lib/core/dsp_coeffs.h."""
    dsp_cfg = config.dsp
    sos_bandpass = design_bandpass_sos(FS_HZ, dsp_cfg.highpass_hz, dsp_cfg.lowpass_hz, dsp_cfg.filter_order)
    sos_notch = design_notch_sos(FS_HZ, dsp_cfg.notch_hz, dsp_cfg.notch_quality_factor)

    def fmt_sos(sos) -> str:
        rows = ",\n  ".join("[" + ", ".join(f"{v:.17g}" for v in row) + "]" for row in sos)
        return f"[\n  {rows},\n]"

    ts = f"""// AUTO-GENERATED by scripts/export_web_fixtures.py — do not hand-edit.
//
// Generated from config/default_config.yaml (dsp section) via the exact
// same scipy.signal.butter / scipy.signal.iirnotch calls used by
// src/bcihand/dsp/filters.py (design_bandpass_sos / design_notch_sos), so
// this is numerically the same filter design as the Python pipeline's
// default configuration (fs={FS_HZ}, highpass={dsp_cfg.highpass_hz}, lowpass={dsp_cfg.lowpass_hz},
// order={dsp_cfg.filter_order}, notch={dsp_cfg.notch_hz}, Q={dsp_cfg.notch_quality_factor}).
//
// Re-run `python scripts/export_web_fixtures.py` after changing
// config/default_config.yaml's dsp section.

export const FS_HZ = {FS_HZ};

/** Each row: [b0, b1, b2, a0, a1, a2] (a0 is always 1.0), scipy SOS format. */
export const BANDPASS_SOS: number[][] = {fmt_sos(sos_bandpass)};

/** Single second-order section, same row format as BANDPASS_SOS. */
export const NOTCH_SOS: number[][] = {fmt_sos(sos_notch)};
"""
    DSP_DIR.mkdir(parents=True, exist_ok=True)
    path = DSP_DIR / "filterCoeffs.generated.ts"
    path.write_text(ts, encoding="utf-8")
    print(f"Wrote {path}")


def export_filter_golden_vector() -> None:
    """Same signal construction as firmware/esp32/lib/core/dsp_golden_vector.h,
    so both embedded ports (C++ and TypeScript) are checked against the same
    reference case."""
    from bcihand.dsp.filters import CausalBlinkBandFilter

    rng = np.random.default_rng(7)
    n = 64
    x = np.concatenate([rng.normal(0, 3.0, 32), np.full(32, 60.0)])

    chain = CausalBlinkBandFilter(
        FS_HZ, highpass_hz=0.5, lowpass_hz=20.0, order=2, notch_hz=60.0, notch_q=30.0,
        baseline_time_constant_s=4.0,
    )
    y = chain.process_block(x)

    data = {
        "_comment": "Same construction as firmware/esp32/lib/core/dsp_golden_vector.h.",
        "input": _round_list(x, 12),
        "expectedOutput": _round_list(y, 12),
        "toleranceUv": 1e-6,
    }
    path = OUT_DIR / "filterGoldenVector.json"
    path.write_text(json.dumps(data, indent=2), encoding="utf-8")
    print(f"Wrote {path}")


def export_pipeline_golden_run(config) -> None:
    """The critical safety-relevant equivalence fixture (project brief
    section 32/33): the full "one of everything" demo scenario, run through
    the real BlinkPipeline, with raw input samples AND every candidate/
    classification/state/gate decision recorded. The TS port replays the
    raw samples and must reproduce the same discrete decisions."""
    events = build_demo_scenario()
    total_duration_s = max(e.onset_s + e.duration_s for e in events) + 5.0

    source = SimulatedEEGSource(fs_hz=FS_HZ, total_duration_s=total_duration_s, events=events, seed=42)
    source.start()
    samples = source.read_samples()

    pipeline = BlinkPipeline(config, fs_hz=FS_HZ)

    candidates = []
    state_events = []
    gate_decisions = []
    filtered_frontal = []

    for s in samples:
        result = pipeline.process_sample(s)
        filtered_frontal.append(round(float(result.frontal_signal), 9))

        if result.candidate is not None:
            row = {
                "startTimeS": round(result.candidate.start_time_s, 6),
                "endTimeS": round(result.candidate.end_time_s, 6),
                "durationS": round(result.candidate.duration_s, 6),
                "widthValid": result.candidate.width_valid,
                "likelyFilterRebound": result.candidate.likely_filter_rebound,
                "peakSign": result.candidate.peak_sign,
            }
            if result.classification is not None:
                row["classification"] = {
                    "isValidBlink": result.classification.is_valid_blink,
                    "confidence": round(result.classification.confidence, 6),
                    "rejectionReasons": result.classification.rejection_reasons,
                }
            candidates.append(row)

        if result.state_event is not None:
            ev = result.state_event
            state_events.append({
                "eventType": ev.event_type.value,
                "timestampS": round(ev.timestamp_s, 6),
                "firstBlinkTimestampS": round(ev.first_blink_timestamp_s, 6),
                "secondBlinkTimestampS": (round(ev.second_blink_timestamp_s, 6) if ev.second_blink_timestamp_s is not None else None),
                "interBlinkIntervalS": (round(ev.inter_blink_interval_s, 6) if ev.inter_blink_interval_s is not None else None),
                "confidence": round(ev.confidence, 6),
            })
            gate_decisions.append({
                "command": result.gate_decision.command.value,
                "confidenceLevel": result.gate_decision.confidence_level.value,
                "reason": result.gate_decision.reason,
            })

    data = {
        "_comment": (
            "AUTO-GENERATED by scripts/export_web_fixtures.py. Python (BlinkPipeline "
            "run against build_demo_scenario(), seed=42) is the golden reference — "
            "the TS pipeline must replay these exact raw samples and reproduce the "
            "same candidates/classifications/state events/commands. Raw samples are "
            "included (not regenerated in JS) so this test never depends on the TS "
            "simulator's RNG matching Python's bit-for-bit."
        ),
        "fsHz": FS_HZ,
        "groundTruth": [{"startS": s, "endS": e, "label": lbl} for s, e, lbl in source.recording.ground_truth],
        "samples": {
            "timestampS": _round_list(source.recording.timestamps, 6),
            "af7": _round_list(source.recording.channels["AF7"], 9),
            "af8": _round_list(source.recording.channels["AF8"], 9),
            "tp9": _round_list(source.recording.channels["TP9"], 9),
            "tp10": _round_list(source.recording.channels["TP10"], 9),
            "accelX": _round_list(source.recording.accel["x"], 9),
            "accelY": _round_list(source.recording.accel["y"], 9),
            "accelZ": _round_list(source.recording.accel["z"], 9),
        },
        "expected": {
            "filteredFrontal": filtered_frontal,
            "candidates": candidates,
            "stateEvents": state_events,
            "gateDecisions": gate_decisions,
        },
    }
    path = OUT_DIR / "pipelineGoldenRun.json"
    path.write_text(json.dumps(data), encoding="utf-8")  # no indent: this file is large, keep it compact
    size_kb = path.stat().st_size / 1024
    print(f"Wrote {path} ({size_kb:.0f} KB) — {len(candidates)} candidates, {len(state_events)} state events")


def main() -> int:
    config = load_config(override_path=False)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    export_filter_coefficients(config)
    export_filter_golden_vector()
    export_pipeline_golden_run(config)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
