#!/usr/bin/env python
"""Generate firmware/esp32/lib/core/dsp_coeffs.h from the same filter design
functions used by the production PC pipeline (dsp/filters.py).

Per project brief section 20, the embedded filter must use the "same sample
rate assumptions, same coefficients, same normalization" as the PC filter —
this script is the single source of truth that guarantees that, rather than
hand-transcribing scipy output into C++ (error-prone and silently goes
stale if config/default_config.yaml's dsp.* values ever change).

Run this whenever config/default_config.yaml's dsp section changes:
    python scripts/generate_esp32_filter_coeffs.py
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from bcihand.dsp.filters import design_bandpass_sos, design_notch_sos  # noqa: E402
from bcihand.utils.config import load_config  # noqa: E402

OUT_PATH = Path(__file__).resolve().parents[1] / "firmware" / "esp32" / "lib" / "core" / "dsp_coeffs.h"


def format_sos_array(name: str, sos) -> str:
    lines = [f"// {name}: {sos.shape[0]} second-order section(s), each [b0, b1, b2, a0, a1, a2] (a0 is always 1.0)."]
    lines.append(f"static const double {name}[{sos.shape[0]}][6] = {{")
    for row in sos:
        values = ", ".join(f"{v:.17g}" for v in row)
        lines.append(f"    {{{values}}},")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    config = load_config(override_path=False)
    fs_hz = config.acquisition.fallback_sample_rate_hz
    dsp_cfg = config.dsp

    sos_bandpass = design_bandpass_sos(fs_hz, dsp_cfg.highpass_hz, dsp_cfg.lowpass_hz, dsp_cfg.filter_order)
    sos_notch = design_notch_sos(fs_hz, dsp_cfg.notch_hz, dsp_cfg.notch_quality_factor)

    header = f"""// AUTO-GENERATED by scripts/generate_esp32_filter_coeffs.py — do not hand-edit.
//
// Generated from config/default_config.yaml (dsp section) via the exact
// same scipy.signal.butter / scipy.signal.iirnotch calls used by
// src/bcihand/dsp/filters.py (design_bandpass_sos / design_notch_sos), so
// this embedded filter is numerically the same design as the PC pipeline's
// default configuration:
//   fs_hz              = {fs_hz}
//   highpass_hz        = {dsp_cfg.highpass_hz}
//   lowpass_hz         = {dsp_cfg.lowpass_hz}
//   filter_order       = {dsp_cfg.filter_order}
//   notch_hz           = {dsp_cfg.notch_hz}
//   notch_quality      = {dsp_cfg.notch_quality_factor}
//
// If config/default_config.yaml's dsp section changes, or the Muse 2's
// real sampling rate is confirmed to differ from fallback_sample_rate_hz
// (WAITING FOR HARDWARE VERIFICATION — see docs/MUSE2_SETUP.md), re-run:
//     python scripts/generate_esp32_filter_coeffs.py
#pragma once

namespace bcihand {{
namespace dsp_coeffs {{

constexpr double kFsHz = {fs_hz};

{format_sos_array("kBandpassSOS", sos_bandpass)}

{format_sos_array("kNotchSOS", sos_notch)}

}}  // namespace dsp_coeffs
}}  // namespace bcihand
"""
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(header, encoding="utf-8")
    print(f"Wrote {OUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
